### ISSUE TITLE
[CRASH]: Crash when selecting team on Windows

### ISSUE THREAD

**Issue by kus** [DEAFPS/SharpTimer#39]
On Windows the server crashes when you choose a team when SharpTimer is loaded. It does not crash when other plugins like GunGame are loaded and you choose a team.

I understand it is some outdated signatures for Windows, just wondering if you can help debug what calls would be getting made when or soon after choosing a team that the CSSharp team can investigate.

The exact same setup works on Ubuntu.

```
CounterStrikeSharp: v166

meta version
 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1282
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Feb  7 2024 19:03:42
    Built from: https://github.com/alliedmodders/metamod-source/commit/3740821
    Build ID: 1282:3740821
    http://www.metamodsource.net/

meta list
Listing 1 plugin:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin

css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 7 plugins loaded.
  [#1:LOADED]: "CS2-Ultimate-Mapchooser" (1.0.0) by Kus (https://steamcommunity.com/id/kus/)
    The Ultimate Mapchooser for CS2!
  [#2:LOADED]: "CS2Rcon" (1.2.0) by LordFetznschaedl
    Allows for server commands to be executed from the client using !rcon
  [#3:LOADED]: "CS2_ExecAfter" (1.0.0) by Kus (https://github.com/kus)
    Executes a command after server event or a delay. exec_after for help
  [#4:LOADED]: "[Custom] Map Configurator" (V. 1.0.2 [Beta]) by Manifest @Road To Glory
    Allow server owners to easily create unique configuration files on a per map basis.
  [#5:LOADING]: "SimpleAdmin" (0.1.2)
  [#6:LOADED]: "SharpTimer" (0.2.1 - 2/10/2024 11:04:20 PM) by DEAFPS https://github.com/DEAFPS/
    A simple CSS Timer Plugin
  [#7:LOADED]: "Remove Map Weapons" (1.0.0) by Kus (https://steamcommunity.com/id/kus/)
    Remove the weapons from the map
```

This is the error it throws in the console:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at CounterStrikeSharp.API.Core.Helpers.InvokeNative(IntPtr)
--------------------------------
   at CounterStrikeSharp.API.Core.ScriptContext.InvokeNativeInternal()
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](IntPtr, System.Object[])
   at CounterStrikeSharp.API.Modules.Memory.VirtualFunction+<>c__DisplayClass2_0`1[[System.IntPtr, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<CreateVoid>b__1(IntPtr)
   at CounterStrikeSharp.API.Modules.Memory.VirtualFunctionVoid`1[[System.IntPtr, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(IntPtr)
   at SharpTimer.SharpTimer.RemovePlayerCollision(CounterStrikeSharp.API.Core.CCSPlayerController)
   at SharpTimer.SharpTimer.TimerOnTick()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at CounterStrikeSharp.API.Core.BasePlugin+<>c__DisplayClass45_0`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<RegisterListener>b__2(CounterStrikeSharp.API.Core.ScriptContext)
   at DynamicClass.InvokeStub_Action`1.Invoke(System.Object, System.Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at CounterStrikeSharp.API.Core.FunctionReference+<>c__DisplayClass3_0.<.ctor>b__0(CounterStrikeSharp.API.Core.fxScriptContext*)
```

**Comment by DEAFPS** [comment]
should be fixed in new release

**Comment by kus** [comment]
@DEAFPS confirming the 0.2.2 has fixed Windows.

Thank you.
